{
    'name': 'Flex Partner Ledger Customization',
    'version': '1.0',
    'summary': '',
    'description': '',
    'category': '',
    'author': 'Sohaib Alamleh|| Flex-ops',
    'website': '',
    'license': '',
    'depends': ['base', 'account','account_reports'],
    'data': [],
    'demo': [''],
    'installable': True,
    'auto_install': False,
}