{
    'name': 'flex landing orders',
    'version': '1.0',
    'summary': 'flex landing orders',
    'description': 'flex landing orders',
    'category': 'Uncategorized',
    'author': 'Abdalrahman Shahrour',
    'website': 'https://www.flex-ops.com',
    'license': 'AGPL-3',
    'depends': ['base', 'sale','purchase', 'contacts', 'fleet','flex_partner_unique_code', 'hr_payroll', 'stock'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
        'security/rules.xml',
        'views/landing_orders.xml',
        'report/report.xml',
        'views/sale_orders.xml',
        'views/purchase_orders.xml',
        # 'views/contacts.xml',
        'views/fleet_vehicle.xml',
        'views/hr_payslip.xml',
        'views/stock_picking.xml',
        'views/landing_source.xml',
    ],
    'installable': True,
    'auto_install': False,
}