{
    'name': 'Flex Product Arabic',
    'version': '1.0',
    'summary': '',
    'description': '',
    'category': '',
    'author': '',
    'website': '',
    'license': '',
    'depends': ['product','purchase','repair','material_purchase_requisitions'],
    'data': ['views/product.xml','views/purchase.xml'],
    'demo': [''],
    'installable': True,
    'auto_install': False,
}