{
    'name': 'Flex Employee Requests',
    'version': '0.1',
    'summary': '',
    'description': '',
    'category': '',
    'author': 'HACHEMI Mohamed Ramzi || Flex-Ops',
    'website': 'https://www.flex-ops.com',
    'license': 'AGPL-3',
    'depends': ['base', 'hr', 'flex_hr_employee', 'hr_expense', 'approvals', 'hr_employee_updation'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'views/employee_transfer_approval.xml',
        'views/employee_renew_iqama.xml',
        'views/business_trip_approval.xml',
        'views/employee_resignation_approval.xml',
        'views/res_config_settings_views.xml',
        'wizards/employee_transfer_reject_wizard.xml',
        'wizards/renew_iqama_reject_wizard.xml',
        'wizards/business_trip_reject_wizard.xml',
        'wizards/resignation_reject_wizard.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'auto_install': False,
}
