{
    'name': 'Flex Approvals',
    'version': '1.0',
    'summary': 'Flexible Approvals',
    'description': 'Flexible Approvals',
    'category': 'Uncategorized',
    'author': 'Abdalrahman Shahrour',
    'website': 'https://www.flex-ops.com',
    'license': 'LGPL-3',
    'depends': ['base', 'approvals', 'hr', 'mail'],
    'data': ['views/approval_category_views.xml',
             'views/approval_request_views.xml',
             ],
    'installable': True,
    'auto_install': False,
}
