{
    'name': 'Flex HR Recruitment',
    'version': '1.0',
    'summary': 'Edit HR Recruitment',
    'description': '',
    'category': '',
    'author': 'Sohaib Alamleh||Flex-ops',
    'website': 'https://www.flex-ops.com',
    'license': '',
    'depends': ['base','hr_recruitment'],
    'data': ['security/ir.model.access.csv',
             'reports/reports.xml',
             'views/rec.xml',
             'views/hr_application.xml',
             'views/res_company.xml',
             'data/sequence.xml',
             'data/mail_template.xml',
             ],
    'demo': [''],
    'installable': True,
    'auto_install': False,
}
